// <auto-generated />
using System;
using Leoni.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leoni.Migrations
{
    [DbContext(typeof(LeoniDbContext))]
    [Migration("20260101161817_add-refreshToken-table")]
    partial class addrefreshTokentable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeRole", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "RoleId")
                        .HasName("PK__Employee__C27FE3F06CCDFC70");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRole", (string)null);
                });

            modelBuilder.Entity("Leoni.Domain.Entities.Component", b =>
                {
                    b.Property<string>("ComponentName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime");

                    b.HasKey("ComponentName")
                        .HasName("PK__Componen__DB06D1C0374B2836");

                    b.ToTable("Component", (string)null);
                });

            modelBuilder.Entity("Leoni.Domain.Entities.Employee", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sessionId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstName");

                    b.Property<string>("HashedPasword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastName");

                    b.HasKey("SessionId")
                        .HasName("PK__Employee__23DB122B8E84CB5A");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Leoni.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermissionId")
                        .HasName("PK__Permissi__EFA6FB2F002B00F2");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("Leoni.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Leoni.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1A67E155C5");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Leoni.Domain.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Status__3214EC074BFE197F");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("Leoni.Domain.Entities.Tasks", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("ActivePart")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ActualMinutes")
                        .HasColumnType("int");

                    b.Property<string>("AssignedByFk")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("CleansingDate")
                        .HasColumnType("date");

                    b.Property<int?>("CompletedMinutesSmv")
                        .HasColumnType("int")
                        .HasColumnName("CompletedMinutesSMV");

                    b.Property<string>("ComponentGroup")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerPn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CustomerPN");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DevExXmllink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DevExXMLLink");

                    b.Property<string>("DocumentComments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FailureDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IBomxmllink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("iBOMXMLLink");

                    b.Property<string>("InternalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LeoniPn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LeoniPN");

                    b.Property<bool?>("NeededForClassification")
                        .HasColumnType("bit");

                    b.Property<bool?>("NeededForValidation")
                        .HasColumnType("bit");

                    b.Property<string>("PartnerDrawing")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReleasedPartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResponsibleComponentEngineerId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TerminalReelDirectionWireSizes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TimeSmv")
                        .HasColumnType("int")
                        .HasColumnName("TimeSMV");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TaskId")
                        .HasName("PK__Tasks__7C6949B1B52E1B57");

                    b.HasIndex("AssignedByFk");

                    b.HasIndex("ComponentName");

                    b.HasIndex("ResponsibleComponentEngineerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("PK__RolePerm__6400A1A808124B35");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("EmployeeRole", b =>
                {
                    b.HasOne("Leoni.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__EmployeeR__Emplo__35BCFE0A");

                    b.HasOne("Leoni.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__EmployeeR__RoleI__36B12243");
                });

            modelBuilder.Entity("Leoni.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Leoni.Domain.Entities.Employee", "Employee")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Leoni.Domain.Entities.Tasks", b =>
                {
                    b.HasOne("Leoni.Domain.Entities.Employee", "AssignedBy")
                        .WithMany("TasksAssigned")
                        .HasForeignKey("AssignedByFk")
                        .HasConstraintName("FK_Tasks_AssignedBy");

                    b.HasOne("Leoni.Domain.Entities.Component", "Component")
                        .WithMany("Tasks")
                        .HasForeignKey("ComponentName")
                        .IsRequired();

                    b.HasOne("Leoni.Domain.Entities.Employee", "ResponsibleComponentEngineer")
                        .WithMany("Tasks")
                        .HasForeignKey("ResponsibleComponentEngineerId")
                        .HasConstraintName("FK_Tasks_Employee");

                    b.HasOne("Leoni.Domain.Entities.Status", "Status")
                        .WithMany("Tasks")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_Status");

                    b.Navigation("AssignedBy");

                    b.Navigation("Component");

                    b.Navigation("ResponsibleComponentEngineer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("Leoni.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK__RolePermi__Permi__3A81B327");

                    b.HasOne("Leoni.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__RolePermi__RoleI__398D8EEE");
                });

            modelBuilder.Entity("Leoni.Domain.Entities.Component", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Leoni.Domain.Entities.Employee", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Tasks");

                    b.Navigation("TasksAssigned");
                });

            modelBuilder.Entity("Leoni.Domain.Entities.Status", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
